// Placeholder. Generated by `pnpm generate-types` against insyta-api OpenAPI schema.
// REGENERAR DESPUES DE WAVE 2A: cuando los endpoints REST esten estables, correr
// `pnpm generate-types` con el backend dev server corriendo en :8000.

export interface paths {
  [path: string]: unknown;
}

export interface components {
  schemas: Record<string, unknown>;
}

export type webhooks = Record<string, never>;
export type operations = Record<string, never>;
